<a href="https://colab.research.google.com/github/presannak/ML_Colabs/blob/main/Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
x = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [5]:
y = np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

In [6]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [7]:
def derivative_sigmoid(x):
  return x*(1-x)

In [8]:
epoch = 5000
lr = 0.1
input_neurons = x.shape[1]
hidden_neurons = 3
output_neurons = 1

In [9]:
wh = np.random.uniform(size=(input_neurons,hidden_neurons))
bh = np.random.uniform(size=(1,hidden_neurons))
wo = np.random.uniform(size=[hidden_neurons,output_neurons])
bo = np.random.uniform(size=[1,output_neurons])

In [11]:
for i in range(epoch):
  hidden_input = np.dot(x,wh)
  hidden_input = hidden_input + bh
  hidden_activation = sigmoid(hidden_input)
  output_layer = np.dot(hidden_activation,wo)
  output = sigmoid(output_layer)

  E = y-output
  slope_output = derivative_sigmoid(output)
  slope_hidden = derivative_sigmoid(hidden_activation)
  d_output = E*slope_output
  error_hidden = d_output.dot(wo.T)
  d_hidden = error_hidden*slope_hidden
  wo+=hidden_activation.T.dot(d_output)*lr
  bo+=np.sum(d_output,axis=0,keepdims=True)*lr
  wh+=x.T.dot(d_hidden)*lr

In [12]:
output

array([[0.9711768 ],
       [0.03391545],
       [0.979196  ]])