<a href="https://colab.research.google.com/github/presannak/Virtual-Academy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
l=[]
print(l)
l.append(1)
print(l)
l.remove(1)
print(l)
l.

[]
[1]
[]


In [ ]:
t=(1,2,3,1)
print(t.index(3))
t.count(1)

2


2

In [ ]:
d={'a':1,'b':2,'c':3}
for i in d:
  print(d.items())

dict_items([('a', 1), ('b', 2), ('c', 3)])
dict_items([('a', 1), ('b', 2), ('c', 3)])
dict_items([('a', 1), ('b', 2), ('c', 3)])


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a.shape)
print(np.zeros((2,2)))
print(np.full((2,2),7))
f=np.arange(1,11,2)
print(f)

(2, 2)
[[0. 0.]
 [0. 0.]]
[[7 7]
 [7 7]]
[1 3 5 7 9]


In [ ]:
g=np.linspace(0.,1.,num=5)
print(g)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
data=np.array([1,2,3])
data[1]
data[0:2]

array([1, 2])

In [ ]:
data=np.array([[1,2,3],[4,5,6]])
print(data)
print(data[0:3,1])

[[1 2 3]
 [4 5 6]]
[2 5]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a.shape

(3, 4)

In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(a)
b=np.array([0,2,0,3])
print(a[np.arange(4),b])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  7  9 16]


In [ ]:
a[np.arange(4),b]+=10
print(a)

[[11  2  3  4]
 [ 5  6 17  8]
 [19 10 11 12]
 [13 14 15 26]]


In [ ]:
a=np.array([1,8,9,-3,2,4,7,9])
print(np.argmax(a))#max
print(np.argmin(a))#min
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a>5)[0])
print(np.where(a>=a[np.argmax(a)])[0])


2
3
[3 0 4 5 6 1 2 7]
[7 2 1 6 5 4 0 3]
[1 2 6 7]
[2 7]


In [ ]:
a=np.array([[1,6],[6,7]])
print(np.where(a>5))


(array([0, 1, 1]), array([1, 0, 1]))


In [ ]:
a=np.array([[0],[1]])
a=np.append(a,[1,2])
print(a)

[0 1 1 2]


In [ ]:
a=np.array([[11,22,13,10],[5,6,7,22],[9,10,11,2],[13,14,15,16]])
a=np.sort(a,axis=1,kind="quicksort")
print(a)

[[10 11 13 22]
 [ 5  6  7 22]
 [ 2  9 10 11]
 [13 14 15 16]]


In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array(([5,6],[7,8]))

v=np.array([9,10])
w=np.array([11,12])
print(x.dot(y))
print(np.dot(x,v))
#Transpose
print(x.T)

[[19 22]
 [43 50]]
[29 67]
[[1 3]
 [2 4]]


In [ ]:
z=np.array([[1],[2],[3],[4]])
print(z)
w=z.squeeze()
print(w)

[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


In [ ]:
#Broadcasting
a=np.array([1,2,3])
print(a+1)

[2 3 4]


In [ ]:
np.array([[1,2,3],[4,5,6]])+np.array([1,2,3])

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
np.array([1,2,3])+np.array([[4],[5],[6]])

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
np.array([1,2])*5

array([ 5, 10])