<a href="https://colab.research.google.com/github/presannak/ML_Colabs/blob/main/RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Loan%20Status.csv")
data

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [ ]:
print(data["Gender"]=="Male")

0       True
1       True
2       True
3       True
4       True
       ...  
609    False
610     True
611     True
612     True
613    False
Name: Gender, Length: 614, dtype: bool


In [ ]:
for i in data:
  print(data.value_counts(i))

Loan_ID
LP001002    1
LP002328    1
LP002305    1
LP002308    1
LP002314    1
           ..
LP001692    1
LP001693    1
LP001698    1
LP001699    1
LP002990    1
Length: 614, dtype: int64
Gender
Male      489
Female    112
dtype: int64
Married
Yes    398
No     213
dtype: int64
Dependents
0     345
1     102
2     101
3+     51
dtype: int64
Education
Graduate        480
Not Graduate    134
dtype: int64
Self_Employed
No     500
Yes     82
dtype: int64
ApplicantIncome
2500     9
4583     6
6000     6
2600     6
5000     5
        ..
3250     1
3246     1
3244     1
3237     1
81000    1
Length: 505, dtype: int64
CoapplicantIncome
0.0        273
2083.0       5
2500.0       5
1666.0       5
1750.0       3
          ... 
1911.0       1
1915.0       1
1929.0       1
1964.0       1
41667.0      1
Length: 287, dtype: int64
LoanAmount
120.0    20
110.0    17
100.0    15
160.0    12
187.0    12
         ..
17.0      1
146.0     1
145.0     1
142.0     1
700.0     1
Length: 203, dtype: int64
Loan

In [ ]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
data.shape

(614, 13)

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
data.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [ ]:
data["Self_Employed"].unique()

array(['No', 'Yes', nan], dtype=object)

In [ ]:
data["Gender"].nunique()

2

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
d=lb.fit_transform(data['Loan_Status'])
d

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [ ]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False)
df_1 = np.array([data['Loan_Status']]).reshape(-1,1)
d1 = onehot_encoder.fit_transform(df_1)
d1

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [ ]:
gd = pd.get_dummies(data['Loan_ID'])
gd

LP001002  LP001003  LP001005  LP001006  LP001008  LP001011  LP001013  \
0           1         0         0         0         0         0         0   
1           0         1         0         0         0         0         0   
2           0         0         1         0         0         0         0   
3           0         0         0         1         0         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
609         0         0         0         0         0         0         0   
610         0         0         0         0         0         0         0   
611         0         0         0         0         0         0         0   
612         0         0         0         0         0         0         0   
613         0         0         0         0         0         0         0   

     LP001014  LP001018  LP001020  ...  LP002959  LP002960  LP002961  \
0           0         0         0  ...         0         0         0   
1           0         0         0  ...         0         0         0   
2           0         0         0  ...         0         0         0   
3           0         0         0  ...         0         0         0   
4           0         0         0  ...         0         0         0   
..        ...       ...       ...  ...       ...       ...       ...   
609         0         0         0  ...         0         0         0   
610         0         0         0  ...         0         0         0   
611         0         0         0  ...         0         0         0   
612         0         0         0  ...         0         0         0   
613         0         0         0  ...         0         0         0   

     LP002964  LP002974  LP002978  LP002979  LP002983  LP002984  LP002990  
0           0         0         0         0         0         0         0  
1           0         0         0         0         0         0         0  
2           0         0         0         0         0         0         0  
3           0         0         0         0         0         0         0  
4           0         0         0         0         0         0         0  
..        ...       ...       ...       ...       ...       ...       ...  
609         0         0         1         0         0         0         0  
610         0         0         0         1         0         0         0  
611         0         0         0         0         1         0         0  
612         0         0         0         0         0         1         0  
613         0         0         0         0         0         0         1  

[614 rows x 614 columns]

In [ ]:
data["Gender"] = data["Gender"].map({"Male":1, "Female":0})
data["Married"] = data["Married"].map({"Yes":1, "No":0})
data["Education"] = data["Education"].map({"Graduate":1, "Not Graduate":0})
data["Dependents"].replace('3+',3,inplace=True)
data["Self_Employed"] = data["Self_Employed"].map({"Yes":1, "No":0})
data["Property_Area"] = data["Property_Area"].map({"Semiurban":1, "Urban":2, "Rural":3})
data["Loan_Status"] = data["Loan_Status"].map({"Y":1, "N":0})

In [ ]:
data

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0    LP001002     1.0      0.0          0          1            0.0   
1    LP001003     1.0      1.0          1          1            0.0   
2    LP001005     1.0      1.0          0          1            1.0   
3    LP001006     1.0      1.0          0          0            0.0   
4    LP001008     1.0      0.0          0          1            0.0   
..        ...     ...      ...        ...        ...            ...   
609  LP002978     0.0      0.0          0          1            0.0   
610  LP002979     1.0      1.0          3          1            0.0   
611  LP002983     1.0      1.0          1          1            0.0   
612  LP002984     1.0      1.0          2          1            0.0   
613  LP002990     0.0      0.0          0          1            1.0   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History  Property_Area  Loan_Status  
0               1.0              2            1  
1               1.0              3            0  
2               1.0              2            1  
3               1.0              2            1  
4               1.0              2            1  
..              ...            ...          ...  
609             1.0              3            1  
610             1.0              3            1  
611             1.0              2            1  
612             1.0              2            1  
613             0.0              1            0  

[614 rows x 13 columns]

In [ ]:
rev_null=['Gender','Married','Dependents','Self_Employed','Credit_History','LoanAmount','Loan_Amount_Term']
data[rev_null] = data[rev_null].replace({np.nan:data['Gender'].mode(),
                                         np.nan:data['Married'].mode(),
                                         np.nan:data['Dependents'].mode(),
                                         np.nan:data['Self_Employed'].mode(),
                                         np.nan:data['Credit_History'].mode(),
                                         np.nan:data['LoanAmount'].mode(),
                                         np.nan:data['Loan_Amount_Term'].mode()})

In [ ]:
data.dropna(inplace=True)

In [ ]:
X = data.drop(columns=['Loan_ID','Loan_Status']).values
y = data['Loan_Status'].values
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=42)

In [ ]:
X_train

array([[1.0, 1.0, '2', ..., 360.0, 1.0, 1],
       [1.0, 0.0, '0', ..., 480.0, 1.0, 2],
       [0.0, 1.0, '0', ..., 360.0, 1.0, 1],
       ...,
       [1.0, 1.0, '1', ..., 360.0, 1.0, 3],
       [1.0, 1.0, '0', ..., 360.0, 1.0, 1],
       [1.0, 1.0, '2', ..., 360.0, 1.0, 2]], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
sta = StandardScaler()
X_train = sta.fit_transform(X_train)
X_test = sta.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
rfc = RandomForestClassifier(criterion = 'entropy',random_state=42)
rfc.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [ ]:
y_pred_test = rfc.predict(X_test)
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.89      0.36      0.52        44
           1       0.78      0.98      0.87       100

    accuracy                           0.79       144
   macro avg       0.83      0.67      0.69       144
weighted avg       0.81      0.79      0.76       144

